apiVersion: apps/v1
kind: Deployment
metadata:
  name: edhmatch
  labels:
    app: edhmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edhmatch
  template:
    metadata:
      labels:
        app: edhmatch
    spec:
      containers:
        - name: edhmatch
          image: docker.io/rkra/edhmatch:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: edhmatch
spec:
  type: NodePort
  selector:
    app: edhmatch
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080